# Add the following in your secrets.yaml file:
# - api_key
# - ota_password
# - wifi_ssid
# - wifi_password
# - ap_password
# - domain
#
# Create a folder named fonts in your ESPHome folder, and copy the 
# files fonts/Arimo-Regular.ttf and fonts/materialdesignicons-webfont.ttf there.
#
# ============================================================ 
# ESPHome Setup
# ============================================================

substitutions:     # Modify these to suit you
  font_direcotry: fonts/
  device_name: touchled
  nice_name: touchled
  width: 320
  height: 240

# Namin
esphome:
  name: ${device_name}                  # Device hostname
  friendly_name: ${nice_name}           # Friendly name shown in Home Assistant
 
# The display uses an esp32
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# Set OTA password, enables updates via ESPHome
ota:
  platform: esphome
  password: !secret ota_password

# Setup WiFi credentials, references the wifi ssid and pass in secrets.yaml
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: $device_name Fallback Hotspot
    password: !secret ap_password

# Allows captive portal access when in fallback mode
captive_portal:


# Create a font to use, add and remove glyphs as needed. 
font:
  - file: 'fonts/Arimo-Regular.ttf'
    id: arimo20
    size: 20
    glyphs: "!\"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZÅÄÖ abcdefghijklmnopqrstuvwxyzåäö"

  - file: ${font_direcotry}materialdesignicons-webfont.ttf         # Defining Material Design Icons as a font. This
    id: mdi_icons                                       # will allow us to use them as button icons.
    size: 48                                            # You can get these glyphs from the https://pictogrammers.com/library/mdi/
    glyphs:                                             # where you choose the icon, and then "copy glyph".
      - 󱁑  # mdi-led-strip-variant
      - 󰈐  # mdi-fan
      - 󰏘  # mdi-pallette
      - 󰤝  # mdi-wall-sconce-flat
      - 󰚵  # lamp
      - 󱟐  # lamp-outline

# ==== Lights ====
light:
# LCD backlight
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: backlight
    restore_mode: ALWAYS_OFF
# rgb led
  - platform: rgb
    name: "Front LED"
    id: front_led
    restore_mode: ALWAYS_OFF
    red: led_red
    green: led_green
    blue: led_blue

# Set the pins for the SPI bus for TFT display and touch controller
spi:
  - id: spi_tft
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: GPIO12
  - id: touch
    clk_pin: GPIO25
    mosi_pin: GPIO32
    miso_pin: GPIO39

# Set the pins to control the backlight and the led
output:
  - platform: ledc
    pin: GPIO21
    id: backlight_pwm
  - platform: ledc
    pin: GPIO22
    id: led_red
    inverted: true
  - platform: ledc
    pin: GPIO17
    id: led_blue 
    inverted: true
  - platform: ledc
    pin: GPIO16
    id: led_green 
    inverted: true


# Defining the display type and properties, and defining the buttons displayed.
display:
  - platform: mipi_spi
    id: my_display
    model: ST7796
    spi_id: spi_tft
    buffer_size: 25%   
    dc_pin: 
      number: GPIO2
      ignore_strapping_warning: true
    cs_pin:
      number: GPIO15
      ignore_strapping_warning: true
    dimensions:
      width: ${width}
      height: ${height}   
    invert_colors: true
    update_interval: never
    auto_clear_enabled: false
    rotation: 90

touchscreen:
  - platform: xpt2046
    spi_id: touch
    cs_pin: GPIO33
    interrupt_pin: GPIO36
    update_interval: 20ms
    threshold: 400
    calibration:
      x_min: 282
      x_max: 3821
      y_min: 217
      y_max: 3740
    transform:
      swap_xy: true
    on_touch:
      then:
        - light.turn_on: backlight
        - lambda: |-
              ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
                  touch.x,
                  touch.y,
                  touch.x_raw,
                  touch.y_raw
                  );

color:
  - id: room_bg_color
    hex: "000000"
  - id: ha_blue
    hex: "51c0f2"
  - id: default_button_bg_color
    hex: "000000"
  - id: default_button_pressed_bg_color
    hex: "D3D3D3"
  - id: btn_1_color
    hex: "FF0000"                    # Red
  - id: btn_2_color
    hex: "FF7F00"                    # Orange  
  - id: btn_3_color
    hex: "FFFF00"                    # Yellow

#time used for nightly antiburn of the display
time:
  - platform: sntp
    on_time:
      - hours: 2,3,4,5
        minutes: 5
        seconds: 0
        then:
          - switch.turn_on: switch_antiburn
      - hours: 2,3,4,5
        minutes: 35
        seconds: 0
        then:
          - switch.turn_off: switch_antiburn

#switch used to start antiburn, present in HA as well 
switch:
  - platform: template
    name: Antiburn    
    id: switch_antiburn
    icon: mdi:television-shimmer
    optimistic: true
    entity_category: "config"
    turn_on_action:
      - logger.log: "Starting Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:
      - lvgl.pause:
          show_snow: true
    turn_off_action:
      - logger.log: "Stopping Antiburn"
      - if:
          condition: lvgl.is_paused
          then:
            - lvgl.resume:
            - lvgl.widget.redraw:

#sets how long the period before considering the screen to be idle, present in HA as well
number:
  - platform: template
    name: LVGL Screen timeout
    optimistic: true
    id: display_timeout
    unit_of_measurement: "s"
    initial_value: 45
    restore_value: true
    min_value: 10
    max_value: 180
    step: 5
    mode: box

#checks the state of the entity (a lamp in my case) and updates the icon according to it
text_sensor:
  - platform: homeassistant
    id: ts_office_light
    entity_id: light.livingroom_window
    on_value:
      then:
        - lvgl.widget.update:
            id: btn_3
            state:
              checked: !lambda return (0 == x.compare(std::string{"on"}));
              disabled: !lambda return ((0 == x.compare(std::string{"unavailable"})) or (0 == x.compare(std::string{"unknown"})));
        - lvgl.label.update:
            id: lbl_btn_3
            text: !lambda |-
              static char buf[10];
              std::string icon;
              if (0 == x.compare(std::string{"on"})) {
                  icon = "󰚵";  // mdi:lamp
              } else {
                  icon = "󱟐";  // mdi:lamp-outline
              }
              snprintf(buf, sizeof(buf), "%s", icon.c_str());
              return buf;

#actual configuration for showing on the screen
lvgl:
  buffer_size: 25%
  on_idle:
    timeout: !lambda "return (id(display_timeout).state * 1000);"
    then:
      - logger.log: "LVGL is idle"
      - light.turn_off: backlight
      - lvgl.pause:

  theme:
    button:
      # This base is overridden by each button's bg_color
      bg_color: 0x000000
      bg_opa: COVER
      border_color: 0x000000
      border_width: 0
      text_color: 0xFFFFFF  # overridden per label using text_color: btn_x_color
      pressed:
        # Light grey for pressed state (used uniformly)
        bg_color: 0xC0C0C0
        bg_grad_color: 0xC0C0C0
        bg_opa: COVER
      checked:
        bg_color: 0x000000
        bg_grad_color: 0x000000
        bg_opa: COVER
        text_color: 0x800080 # purple icon when "checked"... entity is on
  pages:
    - id: main_page
      pad_all: 0
      widgets:
        - obj:
            width: ${width}
            height: ${height}
            bg_color: room_bg_color
            layout:
              type: grid
              grid_columns: [fr(1), fr(1), fr(1), fr(1)]
              grid_rows: [fr(1), fr(1), fr(1)]
            pad_all: 5px
            outline_pad: 5px
            widgets:
              - button:
                  id: btn_1
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 0
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  bg_color: default_button_bg_color
                  pressed:
                    bg_color: default_button_pressed_bg_color
                  widgets:
                    - label:
                        id: lbl_btn_1
                        text: "󱁑"
                        text_font: mdi_icons
                        text_color: btn_1_color
                        align: center
                  on_click:
                    then:
                      - homeassistant.action:
                          action: light.toggle
                          data:
                            entity_id: light.basement_wardrobe_strip
              
              - button:
                  id: btn_2
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 0
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  bg_color: default_button_bg_color
                  pressed:
                    bg_color: default_button_pressed_bg_color
                  widgets:
                    - label:
                        id: lbl_btn_2
                        text: "󰤝"
                        text_font: mdi_icons
                        text_color: btn_2_color
                        align: center
                  on_click:
                    then:
                      - homeassistant.action:
                          action: switch.toggle
                          data:
                            entity_id: switch.shelly_1pm_gen4

              - button:
                  id: btn_3
                  grid_cell_column_pos: 2
                  grid_cell_row_pos: 0
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  bg_color: default_button_bg_color
                  pressed:
                    bg_color: default_button_pressed_bg_color
                  widgets:
                    - label:
                        id: lbl_btn_3
                        text: "󰚵"
                        text_font: mdi_icons
                        text_color: btn_3_color
                        align: center
                  on_click:
                    then:
                      - homeassistant.action:
                          action: light.toggle
                          data:
                            entity_id: light.livingroom_window
